### PR TITLE
Add support to show/hide the month outline

### PR DESCRIPTION
**Pull request by ericvoshall**
Adds a little toggle to show/hide the month outline.

### CODE REVIEW

**Comment by sfsam** [comment]
Thank you for the pull request.

I need to think about this feature. I'm hesitant to add features in general and particularly when they represent minor aesthetic preferences. I'm biased towards bug fixes, better implementations of existing features, or new features that augment functionality or usability. It doesn't mean I won't come around, but it is a hurdle.

As for the implementation, user-facing features need to be localized in Chinese, French, German, Italian, and Spanish. I also think you can just call `-setNeedsDisplay:` instead of `-updateCalendar` in `-setShowMonthOutline:` but maybe I've missed something. What is the reason to call `-updateCalendar`?

A possibility is including this option as a hidden preference. Motivated users could toggle the outline by using the command-line: `defaults write com.mowglii.ItsycalApp ShowMonthOutline -bool NO`. This would keep the UI and codebase a bit simpler and eliminate the need to localize.

**Comment by ericvoshall** [comment]
My thought behind adding this option was that days outside of the current month are already slightly greyed out, so it didn't make sense to also have the outline in addition to that (to me, at least). I also prefer the slightly cleaner look of just having the days greyed out without the outline.

You are right about the `-setNeedsDisplay`, I can update that. I'll defer to you in regards to making it user-facing or not. Thanks for the fast reply!

**Comment by rbnmsc** [comment]
hello, i just want to give a little feedback but in Itsycal i can't seem to find a feedback option so I hope you dont mind if I write here. I just wanted to ask if it was possible to add the option to disable the feature where if you hover with the mouse over a day with an event it shows up that little box with the events of the day. Becouse if I want to just look at the month for example it always brings up that box that covers the whole month for me it would be enough if the events just show if I click on the day. Anyway awesome job with Itsycal, other then that, i absloutely love it, clean and simple and looks awesome.

**Comment by espen** [comment]
I think this would be an improvement. The outline of month results in a cluttered interface. The rest of the GUI is quite minimal but this outline breaks with that IMHO. I think it should be removed by default, but just having this as an hidden option would be great. I understand your concern about adding too many settings though.

**Pull request closed without merging**
