### PR TITLE
Add new icon style "Only Text"

### PR DESCRIPTION
**Pull request by nebular**
This new icon style just draws the text without any outline or solid background, just like OSX does in its default clock if you show the date.

I changed the preference window so instead of a checkbox "Show Icon Outline" it now shows a popup window with three options: Solid, Outline, Text

image

image

### CODE REVIEW

**Comment by sfsam** [comment]
Itsycal can already draw text without the outline or background in the style of the system clock. You can set a datetime patten and check 'Hide icon':

Screen Shot 2019-09-30 at 8 04 32 PM

Also, in general, if you want to draw text in the menubar, you can just set the title of the NSStatusItem's button. You don't need to draw it into an image.

**Comment by nebular** [comment]
OMG!! that is so right !!  😂

**Comment by sfsam** [comment]
I do want to acknowledge your effort here though. I appreciate it. I have some ideas for improving and extending the UI here, but they are much bigger than a small tweak to the interface and are for another time.

**Comment by nebular** [comment]
Thanks for your kind words. I find the app super useful and have replaced the OSX date/time with it. Waiting anxiously for your planned upgrades!

**Pull request closed without merging**
