### PR TITLE
Theme option

### PR DESCRIPTION
**Pull request by ABeltramo**
See [#21](https://github.com/sfsam/Itsycal/issues/21)
themes
A lot of changes here I'll try to explain in brief:

- Added the class ItsyColors. This will be the "hub" for defining new color schemes or behaviour. Every (I hope so 🤕) NSColor hard coded is now replaced with a get from this class.
- Added the preference select to change the actual theme.
- Copied the default theme from your actual color scheme. I know it's not exactly the same but I think it's very convient to have a few colors easily changeable from a single position.

Missing:

- When you change the theme in the preference you have to quit and reopen the app.
- Seems like I can't change the color of the resize handler consistently.
- Also the colors of the highlight days it's odd.
- Proper internalization (if needed) for the new preference panel.

### CODE REVIEW

**Comment by sfsam** [comment]
@ABeltramo It looks like we were working in parallel. I've uploaded a test version with light/dark themes: https://s3.amazonaws.com/itsycal/Itsycal-themes-beta.zip

I believe it addresses some of the issues you listed above. It would be a bit more work to extend beyond 2 themes, but I think that is ok for now. It also still needs to be localized.

**Comment by ABeltramo** [comment]
Can we discuss about the code? I like the idea to have an easy way to implement new themes. In future we can open up to new user selectable color scheme.

**Comment by sfsam** [comment]
@ABeltramo It wouldn't be trivial to add more themes, but it wouldn't be too hard either. As it is, this is a big change and I'd like to see how things go before considering more themes or opening it up to other users. 

As I currently have it, I'm just using a singleton called Themer which has instance methods for the different colors (sort of like your ItsyColors class). Themer only knows about two themes right now (light and dark), but I think it could be extended later.

**Comment by lucasmezencio** [comment]
Plllllsssss! <3

**Pull request closed without merging**
