### PR TITLE
Add Chinese Simplified localization

### PR DESCRIPTION
**Pull request by pluwen**
Wish you like it

### CODE REVIEW

**Comment by sfsam** [comment]
Thank you. Can you provide screenshots of the calendar and all 3 of the preference tabs?

**Comment by pluwen** [comment]
image

image
image
image

**Comment by sfsam** [comment]
Thank you. It looks like the localization needs to be added to the project build settings. I can see the files in the zh-Hans.lproj folder, but they don't show up in the app. Could you add Chinese (Simplified) to the project build settings and make sure the translations show up under InfoPlist.strings, Localizable.strings and MainMenu.strings?

xcode

**Comment by pluwen** [comment]
done

**Comment by sfsam** [comment]
Thank you. Can you fix the text encoding on InfoPlist.strings and Localizable.strings? It is generating a build warning:

screen shot 2017-07-06 at 7 04 58

**Comment by pluwen** [comment]
done again

**Comment by sfsam** [comment]
Thank you.

**Comment by sfsam** [comment]
@pluwen Could you tell me how to translate the following? It is a new alert. I just need the strings to insert into the Localizable.strings file. Thank you.
screen shot 2017-07-17 at 3 03 47 pm

**Comment by pluwen** [comment]
没有可修改的日历。
除非有至少一个有权限修改的日历，否则 Itsycal 无法创建新事件。

**Comment by sfsam** [comment]
Thank you.

**Comment by sfsam** [comment]
@pluwen Hi again. Could you please translate this?

showeventlocation

**Comment by pluwen** [comment]
显示事件位置

**Comment by sfsam** [comment]
So fast! Thank you.

**Comment by sfsam** [comment]
@pluwen Can you translate this please? This is to toggle the dots that appear below the days in the calendar.

digek6avwaetrqx

**Comment by pluwen** [comment]
显示事件圆点

**Pull request merged**
